# Generated by Django 4.2.4 on 2024-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='databas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.CharField(max_length=150)),
                ('val2', models.IntegerField()),
            ],
        ),
    ]
